In [1]:
import numpy as np
import GPyOpt
import GPy
import GPyOpt.models
import GPyOpt.core

from nopast import get_best_evaluation

In [2]:
def hartmann3d(x):
    x = np.atleast_2d(x)

    A = np.array([[3.0, 10.0, 30.0], [0.1,10.0,35.0], [3.0, 10.0, 30.0], [0.1, 10.0, 35.0]])
    P = np.array([[3689, 1170, 2673],[4699, 4387, 7470],[1091, 8732, 5547],[381, 5743, 8828]]) * 1e-4
    alpha = np.array([[1.0, 1.2, 3.0, 3.2]]).T
    
    expTerm = np.diagonal(-1*((x[:,np.newaxis,:] - P[np.newaxis,:,:]) ** 2)@A.T, axis1=1,axis2=2)
    
    ret = -1*(np.exp(expTerm)@alpha)
    
    return ret

mixed_domain =[{'name': 'var1', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var2', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var3', 'type': 'continuous', 'domain': (0,1)}]
space = GPyOpt.Design_space(mixed_domain)

In [3]:
acquisitions = [
    {
        'type': 'ei',
        'epsilon': 1e-2
    },
    {
        'type': 'pi',
        'epsilon': 1e-2
    },
    {
        'type': 'lcb',
        'upsilon': 0.2,
        'delta': 0.1
    },
]

In [4]:
X_init = np.array([[0.5, 0.5, 0.5], [0.25, 0.25, 0.25],[0.75, 0.75, 0.75]])
y_init = hartmann3d(X_init)

In [9]:
evaluations, scores = get_best_evaluation(X_init, y_init, space, acquisitions, hartmann3d, factor=0.7, iterations=10, eta=4)

In [10]:
evaluations

array([[ 0.5       ,  0.5       ,  0.5       , -0.62802202],
       [ 0.25      ,  0.25      ,  0.25      , -0.7996378 ],
       [ 0.75      ,  0.75      ,  0.75      , -1.89605115],
       [ 0.78975499,  0.75727933,  0.89890343, -2.35484043],
       [ 0.74260799,  0.74950753,  0.76329168, -2.01739138],
       [ 0.75136849,  0.85684889,  0.7397246 , -1.18623933],
       [ 0.75183117,  0.75346942,  0.74948335, -1.86736012],
       [ 0.75997014,  0.7460527 ,  0.75214213, -1.92888106],
       [ 0.75203377,  0.72087785,  0.74881332, -2.06779769],
       [ 0.750273  ,  0.77432827,  0.78547303, -1.99030043],
       [ 0.76603129,  0.75215461,  0.76243074, -1.96822424],
       [ 0.80104902,  0.75214976,  0.7498625 , -1.82618266],
       [ 0.86603955,  0.75146961,  0.75909642, -1.8520717 ]])

In [11]:
scores

[array([1.94715567, 2.32703795, 1.59580642]),
 array([2.95316507, 4.06689208, 2.65664372]),
 array([3.56721605, 4.38365508, 3.34001047]),
 array([4.81362315, 5.46402224, 4.22907766]),
 array([4.95434084, 6.13464606, 4.54550508]),
 array([5.70611003, 6.73276881, 4.99757719]),
 array([5.66837013, 6.79001074, 5.01595196]),
 array([5.66836946, 7.10576784, 5.21158297]),
 array([6.09373031, 7.4018292 , 5.77880791]),
 array([6.38721413, 7.59379692, 6.17142056])]