In [1]:
import numpy as np
import GPyOpt
import GPy
import GPyOpt.models
import GPyOpt.core

from nopast import get_best_evaluation

In [2]:
def hartmann3d(x):
    x = np.atleast_2d(x)

    A = np.array([[3.0, 10.0, 30.0], [0.1,10.0,35.0], [3.0, 10.0, 30.0], [0.1, 10.0, 35.0]])
    P = np.array([[3689, 1170, 2673],[4699, 4387, 7470],[1091, 8732, 5547],[381, 5743, 8828]]) * 1e-4
    alpha = np.array([[1.0, 1.2, 3.0, 3.2]]).T
    
    expTerm = np.diagonal(-1*((x[:,np.newaxis,:] - P[np.newaxis,:,:]) ** 2)@A.T, axis1=1,axis2=2)
    
    ret = -1*(np.exp(expTerm)@alpha)
    
    return ret

mixed_domain =[{'name': 'var1', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var2', 'type': 'continuous', 'domain': (0,1)},
               {'name': 'var3', 'type': 'continuous', 'domain': (0,1)}]
space = GPyOpt.Design_space(mixed_domain)

In [3]:
acquisitions = [
    {
        'type': 'ei',
        'epsilon': 1e-2
    },
    {
        'type': 'pi',
        'epsilon': 1e-2
    },
    {
        'type': 'lcb',
        'upsilon': 0.2,
        'delta': 0.1
    },
]

In [4]:
X_init = np.array([[0.5, 0.5, 0.5], [0.25, 0.25, 0.25],[0.75, 0.75, 0.75]])
y_init = hartmann3d(X_init)

In [5]:
evaluations, scores = get_best_evaluation(X_init, y_init, space, acquisitions, hartmann3d, factor=0.7, iterations=100, eta=4)

In [6]:
evaluations

array([[ 0.5       ,  0.5       ,  0.5       , -0.62802202],
       [ 0.25      ,  0.25      ,  0.25      , -0.7996378 ],
       [ 0.75      ,  0.75      ,  0.75      , -1.89605115],
       [ 0.74960626,  0.23812298,  0.86444571, -1.46325633],
       [ 0.75821313,  0.75841898,  0.75046367, -1.83606304],
       [ 0.66648176,  0.77825801,  0.75064913, -1.81959368],
       [ 0.75137042,  0.75135402,  0.75345624, -1.91432768],
       [ 0.75000299,  0.75233792,  0.58716263, -1.01903411],
       [ 0.75036678,  0.70352508,  0.67987402, -1.52291383],
       [ 0.75168439,  0.74125018,  0.67648821, -1.38742979],
       [ 0.74997406,  0.75394552,  0.75029863, -1.8730018 ],
       [ 0.75192308,  0.73405001,  0.73795666, -1.88803615],
       [ 0.75325395,  0.75155364,  0.75162942, -1.89584936],
       [ 0.76271418,  0.75035724,  0.80310323, -2.29906026],
       [ 0.67146721,  0.76379473,  0.73613965, -1.80872193],
       [ 0.75087111,  0.75940527,  0.86587951, -2.43911907],
       [ 0.75196401,  0.

In [7]:
scores

[array([1.19675823, 1.80262995, 1.19707081]),
 array([2.75988291, 3.3200383 , 2.68236341]),
 array([3.33979432, 3.82168612, 3.28675134]),
 array([4.27113659, 4.8630188 , 4.23487668]),
 array([5.00094766, 5.51404432, 4.7440801 ]),
 array([5.44966509, 5.94717756, 5.13417087]),
 array([5.24358305, 5.72005698, 5.02254874]),
 array([5.5340003 , 6.09612663, 5.2572159 ]),
 array([5.40616304, 6.29420716, 5.18399197]),
 array([5.75595587, 6.54965884, 5.46844361]),
 array([5.88740689, 6.66057824, 5.51014448]),
 array([5.73497968, 6.27651122, 5.4602362 ]),
 array([5.81909915, 6.68540916, 5.7956058 ]),
 array([5.75674406, 7.03332401, 5.74038506]),
 array([5.93874262, 7.23805131, 5.98639499]),
 array([5.97197539, 7.27919757, 5.88148807]),
 array([6.51901935, 7.48305733, 6.30734348]),
 array([6.19703486, 6.95004579, 6.11720696]),
 array([6.2908486 , 7.25906154, 6.0978889 ]),
 array([6.22251177, 7.3241692 , 5.91934591]),
 array([6.60158943, 7.53431173, 6.21080712]),
 array([6.38860595, 7.20259822, 6.